
# example app - prod profile not active by default
# set 'spring.profiles.active=prod' or 'prodguard.force=true' to run checks
prodguard:
  force: true

  severities:
    PG-001: ERROR
    PG-002: INFO
    PG-005: WARN
    PG-006: DISABLED

  report-only: true
  
  premium:
      enabled: true
